const express = require('express')
const passport = require('../config/passport')
const router = express.Router()
const userController = require('../controllers/user-controller')
const productController = require('../controllers/product-controller')
const cartController = require('../controllers/cart-controller')
const { authenticated, fieldExamine } = require('../middleware/auth')
const localAuthenticate = passport.authenticate('local', { session: false })
const upload = require('../middleware/multer')
const { apiErrorHandler } = require('../middleware/error-handler')

router.post('/login', fieldExamine, localAuthenticate, userController.login)
router.get('/products', authenticated, productController.getProducts)
router.get('/products/seller', authenticated, productController.getProductsByShop)
router.post('/products/new', authenticated, productController.addProduct)
router.post('/products/search', authenticated, productController.searchProducts)
router.post('/products/add', authenticated, upload.single('image'), productController.addProduct)
router.get('/products/:product_id', authenticated, productController.getProduct)
router.put('/products/edit', authenticated, upload.single('image'), productController.editProduct)
router.get('/carts', authenticated, cartController.getCarts)
router.post('/carts/add', authenticated, cartController.addToCart)
router.put('/carts/edit', authenticated, cartController.editCarts)
router.put('/carts/buy', authenticated, cartController.buyProducts)

router.use('/', apiErrorHandler)
module.exports = router
